//! bridge-core — shared types and the canonical cross-chain hashing.
//!
//! THE HASH IS SACRED. [`submission_id`] / [`submission_id_with_auto`] must
//! reproduce, byte-for-byte, the Solidity `BridgeHash` library used by the Gate
//! contract. The Phase-3 equivalence test (`tests/equivalence.rs`) locks this in
//! against fixtures generated by Foundry.

use alloy_primitives::{keccak256, Address, B256, U256};

mod submission;
pub use submission::Submission;

pub mod allow;
pub mod store;

#[cfg(feature = "abi")]
pub mod abi;

// Key custody for the relayer nodes. Needs alloy's local signer / keystore, so
// it rides the same `abi` feature the validator and keeper already enable.
#[cfg(feature = "abi")]
pub mod signer;

#[cfg(feature = "http")]
pub mod remote;

#[cfg(feature = "axum-auth")]
pub mod auth;

/// Domain-separating prefix, matching `BridgeHash.SUBMISSION_PREFIX` in Solidity.
pub const SUBMISSION_PREFIX: u64 = 1;

/// Optional execution payload attached to a transfer.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct AutoParams {
    pub execution_fee: U256,
    pub flags: U256,
    pub fallback_address: Vec<u8>,
    pub data: Vec<u8>,
    /// Packed source-chain sender (20 bytes for an EVM address).
    pub native_sender: Vec<u8>,
}

/// `debridgeId = keccak256(abi.encodePacked(nativeChainId, nativeToken))`.
pub fn debridge_id(native_chain_id: U256, native_token: Address) -> B256 {
    let mut packed = Vec::with_capacity(32 + 20);
    packed.extend_from_slice(&native_chain_id.to_be_bytes::<32>());
    packed.extend_from_slice(native_token.as_slice());
    keccak256(packed)
}

/// The 7-field packed base of every submissionId (unhashed), matching
/// `BridgeHash.packedSubmission`.
fn packed_submission(
    debridge_id: B256,
    amount: U256,
    chain_id_from: U256,
    chain_id_to: U256,
    nonce: U256,
    receiver: &[u8],
) -> Vec<u8> {
    let mut packed = Vec::with_capacity(32 * 6 + receiver.len());
    packed.extend_from_slice(&U256::from(SUBMISSION_PREFIX).to_be_bytes::<32>());
    packed.extend_from_slice(debridge_id.as_slice());
    packed.extend_from_slice(&chain_id_from.to_be_bytes::<32>());
    packed.extend_from_slice(&chain_id_to.to_be_bytes::<32>());
    packed.extend_from_slice(&amount.to_be_bytes::<32>());
    packed.extend_from_slice(receiver);
    packed.extend_from_slice(&nonce.to_be_bytes::<32>());
    packed
}

/// submissionId for a transfer WITHOUT an execution payload.
pub fn submission_id(
    debridge_id: B256,
    amount: U256,
    chain_id_from: U256,
    chain_id_to: U256,
    nonce: U256,
    receiver: &[u8],
) -> B256 {
    keccak256(packed_submission(
        debridge_id,
        amount,
        chain_id_from,
        chain_id_to,
        nonce,
        receiver,
    ))
}

/// submissionId for a transfer WITH an execution payload.
pub fn submission_id_with_auto(
    debridge_id: B256,
    amount: U256,
    chain_id_from: U256,
    chain_id_to: U256,
    nonce: U256,
    receiver: &[u8],
    auto: &AutoParams,
) -> B256 {
    let mut packed = packed_submission(debridge_id, amount, chain_id_from, chain_id_to, nonce, receiver);
    packed.extend_from_slice(&auto.execution_fee.to_be_bytes::<32>());
    packed.extend_from_slice(&auto.flags.to_be_bytes::<32>());
    packed.extend_from_slice(keccak256(&auto.fallback_address).as_slice());
    packed.extend_from_slice(keccak256(&auto.data).as_slice());
    packed.extend_from_slice(keccak256(&auto.native_sender).as_slice());
    keccak256(packed)
}
