[source]
chain_id = 1339
rpc = "http://127.0.0.1:8547"
gate = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
start_block = 0
block_confirmation = 0
poll_interval_ms = 500
max_block_range = 1000
state_file = "/home/nath/project/debridge-node/bridge/.e2e-logs/val-C-state.json"

[signer]
private_key = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

[store]
dir = "/home/nath/project/debridge-node/bridge/sig-store-data"
