//! Phase 3 — cross-language submissionId equivalence.
//!
//! Reads the fixtures generated by Foundry (`forge test --match-contract GenFixtures`)
//! and asserts that the Rust hashing reproduces every Solidity-computed id
//! byte-for-byte. If this ever fails, no validator signature would verify.

use std::path::PathBuf;

use alloy_primitives::{B256, U256};
use bridge_core::{AutoParams, Submission};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixtures {
    fixtures: Vec<Fixture>,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    #[serde(rename = "debridgeId")]
    debridge_id: String,
    amount: String,
    #[serde(rename = "chainIdFrom")]
    chain_id_from: u64,
    #[serde(rename = "chainIdTo")]
    chain_id_to: u64,
    nonce: u64,
    receiver: String,
    #[serde(rename = "hasAuto")]
    has_auto: bool,
    #[serde(rename = "executionFee")]
    execution_fee: String,
    flags: String,
    #[serde(rename = "fallbackAddress")]
    fallback_address: String,
    data: String,
    #[serde(rename = "nativeSender")]
    native_sender: String,
    #[serde(rename = "submissionId")]
    submission_id: String,
}

fn bytes(hex_str: &str) -> Vec<u8> {
    let s = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    if s.is_empty() {
        return Vec::new();
    }
    hex::decode(s).expect("invalid hex in fixture")
}

fn dec(s: &str) -> U256 {
    U256::from_str_radix(s, 10).expect("invalid decimal in fixture")
}

fn fixtures_path() -> PathBuf {
    // crates/bridge-core -> ../../contracts/fixtures/submission_ids.json
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../contracts/fixtures/submission_ids.json")
}

#[test]
fn rust_matches_solidity_for_all_fixtures() {
    let path = fixtures_path();
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "could not read {} ({e}). Run: forge test --match-contract GenFixtures",
            path.display()
        )
    });
    let parsed: Fixtures = serde_json::from_str(&raw).expect("invalid fixtures json");

    assert!(parsed.fixtures.len() >= 3, "expected at least 3 fixtures");

    for f in &parsed.fixtures {
        let sub = Submission {
            debridge_id: f.debridge_id.parse::<B256>().expect("bad debridgeId"),
            amount: dec(&f.amount),
            chain_id_from: U256::from(f.chain_id_from),
            chain_id_to: U256::from(f.chain_id_to),
            nonce: U256::from(f.nonce),
            receiver: bytes(&f.receiver),
            auto: if f.has_auto {
                Some(AutoParams {
                    execution_fee: dec(&f.execution_fee),
                    flags: dec(&f.flags),
                    fallback_address: bytes(&f.fallback_address),
                    data: bytes(&f.data),
                    native_sender: bytes(&f.native_sender),
                })
            } else {
                None
            },
        };

        let expected = f.submission_id.parse::<B256>().expect("bad submissionId");
        let got = sub.compute_id();
        assert_eq!(
            got, expected,
            "submissionId mismatch for fixture '{}': rust={got:#x} solidity={expected:#x}",
            f.name
        );
    }
}
